name = "AlgebraicInterfaces"
uuid = "23cfdc9f-0504-424a-be1f-4892b28e2f0c"
authors = ["Owen Lynch <root@owenlynch.org>"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
